### PR TITLE
Media queries params support added

### PR DESCRIPTION
**Pull request by radist2s**
Also <code>eachDecl</code> is deprecated.

### CODE REVIEW

**Comment by shauns** [comment]
Happy to take this but there's a small linting error in `test.js`

**Comment by radist2s** [comment]
I updated <code>test.js</code>

**Comment by shauns** [comment]
Brilliant, thanks a bunch for the PR 🚀

**Comment by radist2s** [comment]
Nice. Why don't you want to publish updated module on npm?

**Comment by shauns** [comment]
Forgot to tag - Travis should be on the case now.

**Pull request merged**
